apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: vpc-test
  namespace: edu
spec:
  module:
    source: git::https://github.com/DikshikaJain/proton-demo.git//vpc-test/?ref=2.0.3
  organization: eks-org
  secretsMountPath: /tmp/secrets
  variables:
  - environmentVariable: true
    key: AWS_DEFAULT_REGION
    sensitive: false
    valueFrom:
      configMapKeyRef:
        key: region
        name: aws-configurationvpc-test
  - environmentVariable: true
    key: AWS_ACCESS_KEY_ID
    sensitive: true
  - environmentVariable: true
    key: AWS_SECRET_ACCESS_KEY
    sensitive: true
  - environmentVariable: true
    key: AWS_SESSION_TOKEN
    sensitive: true
  - environmentVariable: true
    key: CONFIRM_DESTROY
    sensitive: false
    value: '1'
